"""
            COMPILADOR PYTHON ONLINE.
    CODIFIQUE, COMPILE EXECUTE E DEPURE PROGAMAS PYTHON ON-LINE.
ESCREVA SEU CÓDIGO NESTE EDITOR E PRESSIONE O BOTÃO "EXECUTAR" PARA EXECUTÁ-LO.





"""
print("Hello, world!")
#print("hello world!") 

